package elbv2

import (
	b "github.com/CoverGenius/cloudwatch-prometheus-exporter/base"
	h "github.com/CoverGenius/cloudwatch-prometheus-exporter/helpers"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/cloudwatch"
)

// ALBMetrics is a map of default MetricDescriptions for this namespace
var ALBMetrics = map[string]*b.MetricDescription{
	"ActiveConnectionCount": {
		Help:       aws.String("The total number of concurrent TCP connections active from clients to the load balancer and from the load balancer to targets"),
		OutputName: aws.String("alb_alive_connection_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"ClientTLSNegotiationErrorCount": {
		Help:       aws.String("The number of TLS connections initiated by the client that did not establish a session with the load balancer. Possible causes include a mismatch of ciphers or protocols"),
		OutputName: aws.String("alb_client_tls_negotiation_error_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"ConsumedLCUs": {
		Help:       aws.String("The number of load balancer capacity units (LCU) used by your load balancer"),
		OutputName: aws.String("alb_consumed_lcus"),
		Statistic:  h.StringPointers("Average"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HealthyHostCount": {
		Help:       aws.String("The number of targets that are considered healthy"),
		OutputName: aws.String("alb_healthy_host_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HTTPCode_ELB_4XX_Count": {
		Help:       aws.String("The number of HTTP 4XX client error codes that originate from the load balancer. Client errors are generated when requests are malformed or incomplete"),
		OutputName: aws.String("alb_httpcode_elb_4xx_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HTTPCode_ELB_502_Count": {
		Help:       aws.String("The number of HTTP 502 error codes that originate from the load balancer"),
		OutputName: aws.String("alb_httpcode_elb_502_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HTTPCode_ELB_503_Count": {
		Help:       aws.String("The number of HTTP 503 error codes that originate from the load balancer"),
		OutputName: aws.String("alb_httpcode_elb_503_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HTTPCode_ELB_504_Count": {
		Help:       aws.String("The number of HTTP 504 error codes that originate from the load balancer"),
		OutputName: aws.String("alb_httpcode_elb_504_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HTTPCode_ELB_5XX_Count": {
		Help:       aws.String("The number of HTTP 5XX server error codes that originate from the load balancer. This count does not include any response codes generated by the targets"),
		OutputName: aws.String("alb_httpcode_elb_5xx_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HTTPCode_Target_2XX_Count": {
		Help:       aws.String("The number of HTTP response codes generated by the targets"),
		OutputName: aws.String("alb_httpcode_target_2xx_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HTTPCode_Target_3XX_Count": {
		Help:       aws.String("The number of HTTP response codes generated by the targets"),
		OutputName: aws.String("alb_httpcode_target_3xx_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HTTPCode_Target_4XX_Count": {
		Help:       aws.String("The number of HTTP response codes generated by the targets"),
		OutputName: aws.String("alb_httpcode_target_4xx_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HTTPCode_Target_5XX_Count": {
		Help:       aws.String("The number of HTTP response codes generated by the targets"),
		OutputName: aws.String("alb_httpcode_target_5xx_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"NewConnectionCount": {
		Help:       aws.String("The total number of new TCP connections established from clients to the load balancer and from the load balancer to targets"),
		OutputName: aws.String("alb_new_connection_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"ProcessedBytes": {
		Help:       aws.String("The total number of bytes processed by the load balancer over IPv4 and IPv6. This count includes traffic to and from clients and Lambda functions, and traffic from an Identity Provider (IdP) if user authentication is enabled"),
		OutputName: aws.String("alb_processed_bytes"),
		Statistic:  h.StringPointers("Average"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"RequestCount": {
		Help:       aws.String("The number of requests processed over IPv4 and IPv6. This count includes only the requests with a response generated by a target of the load balancer"),
		OutputName: aws.String("alb_request_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"RequestCountPerTarget": {
		Help:       aws.String("The average number of requests received by each target in a target group. You must specify the target group using the TargetGroup dimension. This metric does not apply if the target is a Lambda function"),
		OutputName: aws.String("alb_request_count_per_target"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"RuleEvaluations": {
		Help:       aws.String("The number of rules processed by the load balancer given a request rate averaged over an hour"),
		OutputName: aws.String("alb_rule_evaluations"),
		Statistic:  h.StringPointers("Average"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"TargetConnectionErrorCount": {
		Help:       aws.String("The number of connections that were not successfully established between the load balancer and target. This metric does not apply if the target is a Lambda function"),
		OutputName: aws.String("alb_target_connection_error_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"TargetResponseTime": {
		Help:       aws.String("The time elapsed, in seconds, after the request leaves the load balancer until a response from the target is received. This is equivalent to the target_processing_time field in the access logs"),
		OutputName: aws.String("alb_target_response_time"),
		Statistic:  h.StringPointers("Average", "Maximum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"UnHealthyHostCount": {
		Help:       aws.String("The number of targets that are considered unhealthy"),
		OutputName: aws.String("alb_unhealthy_host_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
}

// NLBMetrics is a map of default MetricDescriptions for this namespace
var NLBMetrics = map[string]*b.MetricDescription{
	"ActiveFlowCount": {
		Help:       aws.String("The total number of concurrent flows (or connections) from clients to targets. This metric includes connections in the SYN_SENT and ESTABLISHED states. TCP connections are not terminated at the load balancer, so a client opening a TCP connection to a target counts as a single flow"),
		OutputName: aws.String("nlb_active_flow_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"ConsumedLCUs": {
		Help:       aws.String("The number of load balancer capacity units (LCU) used by your load balancer"),
		OutputName: aws.String("nlb_consumed_lcus"),
		Statistic:  h.StringPointers("Average"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"HealthyHostCount": {
		Help:       aws.String("The number of targets that are considered healthy"),
		OutputName: aws.String("nlb_healthy_host_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"NewFlowCount": {
		Help:       aws.String("The total number of new flows (or connections) established from clients to targets in the time period"),
		OutputName: aws.String("nlb_new_flow_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"ProcessedBytes": {
		Help:       aws.String("The total number of bytes processed by the load balancer, including TCP/IP headers. This count includes traffic to and from targets, minus health check traffic"),
		OutputName: aws.String("nlb_processed_bytes"),
		Statistic:  h.StringPointers("Average"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"TCP_Client_Reset_Count": {
		Help:       aws.String("The total number of reset (RST) packets sent from a client to a target. These resets are generated by the client and forwarded by the load balancer"),
		OutputName: aws.String("nlb_tcp_client_reset_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"TCP_ELB_Reset_Count": {
		Help:       aws.String("The total number of reset (RST) packets generated by the load balancer"),
		OutputName: aws.String("nlb_tcp_elb_reset_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"TCP_Target_Reset_Count": {
		Help:       aws.String("The total number of reset (RST) packets sent from a target to a client. These resets are generated by the target and forwarded by the load balancer"),
		OutputName: aws.String("nlb_tcp_target_reset_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
	"UnHealthyHostCount": {
		Help:       aws.String("The number of targets that are considered unhealthy"),
		OutputName: aws.String("nlb_unhealthy_host_count"),
		Statistic:  h.StringPointers("Average", "Sum"),
		Dimensions: []*cloudwatch.Dimension{},
	},
}
