package elb

import (
	b "github.com/CoverGenius/cloudwatch-prometheus-exporter/base"
	h "github.com/CoverGenius/cloudwatch-prometheus-exporter/helpers"
	"github.com/aws/aws-sdk-go/service/cloudwatch"
)

// Metrics is a map of default MetricDescriptions for this namespace
var Metrics = map[string]*b.ConfigMetric{
	"BackendConnectionErrors": {
		Help:          ("The number of connections that were not successfully established between the load balancer and the registered instances. Because the load balancer retries the connection when there are errors, this count can exceed the request rate. Note that this count also includes any connection errors related to health checks"),
		OutputName:    ("clb_backend_connection_errors"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"EstimatedALBActiveConnectionCount": {
		Help:          ("The estimated number of concurrent TCP connections active from clients to the load balancer and from the load balancer to targets"),
		OutputName:    ("clb_estimated_alb_active_connection_count"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"EstimatedALBConsumedLCUs": {
		Help:          ("The estimated number of load balancer capacity units (LCU) used by an Application Load Balancer"),
		OutputName:    ("clb_estimated_alb_consumed_lcus"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"EstimatedALBNewConnectionCount": {
		Help:          ("The estimated number of new TCP connections established from clients to the load balancer and from the load balancer to targets"),
		OutputName:    ("clb_estimated_alb_new_connection_count"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"EstimatedProcessedBytes": {
		Help:          ("The estimated number of bytes processed by an Application Load Balancer"),
		OutputName:    ("clb_estimated_processed_bytes"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"HealthyHostCount": {
		Help:          ("The number of healthy instances registered with your load balancer. A newly registered instance is considered healthy after it passes the first health check"),
		OutputName:    ("clb_healthy_host_count"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"HTTPCode_Backend_2XX": {
		Help:          ("The number of HTTP response codes generated by registered instances. This count does not include any response codes generated by the load balancer"),
		OutputName:    ("clb_httpcode_backend_2xx"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"HTTPCode_Backend_3XX": {
		Help:          ("The number of HTTP response codes generated by registered instances. This count does not include any response codes generated by the load balancer"),
		OutputName:    ("clb_httpcode_backend_3xx"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"HTTPCode_Backend_4XX": {
		Help:          ("The number of HTTP response codes generated by registered instances. This count does not include any response codes generated by the load balancer"),
		OutputName:    ("clb_httpcode_backend_4xx"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"HTTPCode_Backend_5XX": {
		Help:          ("The number of HTTP response codes generated by registered instances. This count does not include any response codes generated by the load balancer"),
		OutputName:    ("clb_httpcode_backend_5xx"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"HTTPCode_ELB_5XX": {
		Help:          ("The number of HTTP 5XX server error codes generated by the load balancer. This count does not include any response codes generated by the registered instances. The metric is reported if there are no healthy instances registered to the load balancer, or if the request rate exceeds the capacity of the instances (spillover) or the load balancer"),
		OutputName:    ("clb_httpcode_elb_5xx"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"Latency": {
		Help:          ("[HTTP listener] The total time elapsed, in seconds, from the time the load balancer sent the request to a registered instance until the instance started to send the response headers.[TCP listener] The total time elapsed, in seconds, for the load balancer to successfully establish a connection to a registered instance"),
		OutputName:    ("clb_latency"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"RequestCount": {
		Help:          ("The number of requests completed or connections made during the specified interval (1 or 5 minutes)"),
		OutputName:    ("clb_request_count"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"SurgeQueueLength": {
		Help:          ("The total number of requests (HTTP listener) or connections (TCP listener) that are pending routing to a healthy instance. The maximum size of the queue is 1,024. Additional requests or connections are rejected when the queue is full"),
		OutputName:    ("clb_surge_queue_length"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
	"UnHealthyHostCount": {
		Help:          ("The number of unhealthy instances registered with your load balancer"),
		OutputName:    ("clb_unhealthy_host_count"),
		Statistics:    h.StringPointers("Average"),
		PeriodSeconds: 300,
		Dimensions:    []*cloudwatch.Dimension{},
	},
}
